version: 2

jobs:
  build:
    environment:
      image_user: hyperknot
      image_repo: baseimage16

    docker:
      - image: circleci/python:3.7

    steps:
      - checkout
      - setup_remote_docker

      - run: sudo docker version

      - run:
          command: sudo docker build -t $image_user/$image_repo:build_cache .
          working_directory: image

      - run: sudo pip install docker-squash --disable-pip-version-check
      - run: sudo docker-squash -t $image_user/$image_repo:$CIRCLE_TAG $image_user/$image_repo:build_cache

      - run: sudo docker images

      - run: sudo docker push $image_user/$image_repo:$CIRCLE_TAG
