version: 2

jobs:
  build:
    environment:
      image_user: hyperknot
      image_repo: baseimage16

    docker:
      - image: circleci/python:3.7

    steps:
      - checkout
      - run: env
      - run: echo $CIRCLE_TAG
      # - setup_remote_docker

      # - run: docker version

      # - run:
          # command: docker build -t $image_user/$image_repo:build_cache .
          # working_directory: image

      # - run: sudo pip install docker-squash --disable-pip-version-check
      # - run: docker-squash -t $image_user/$image_repo:$CIRCLE_TAG $image_user/$image_repo:build_cache

      # - run: docker images

      # - run: docker push $image_user/$image_repo:$CIRCLE_TAG


workflows:
  version: 2
  tagged-build:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*/
          # tags:
            # only: /^v.*/
